name: "Pull Request Labeler"
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        sync-labels: true
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"