name: "Pull Request Labeler"
on:
  on:
  - pull_request_target

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        sync-labels: true
        repo-token: "${{ secrets.GITHUB_TOKEN }}"