name: "Pull Request Labeler"
on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        sync-labels: true
      with:
        repo-token: "${{ secrets.MYSECRET }}"